//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LANChat.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LANChat.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon BroadcastIcon {
            get {
                object obj = ResourceManager.GetObject("BroadcastIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap btnSendMessage {
            get {
                object obj = ResourceManager.GetObject("btnSendMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream done {
            get {
                return ResourceManager.GetStream("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Emoticons&gt;
        ///  &lt;Emoticon Code=&quot;emot smile&quot; Description=&quot;Smile&quot; ImageKey=&quot;img_emot2_smile&quot;&gt;
        ///    &lt;Text&gt;:)&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Code=&quot;emot grin&quot; Description=&quot;Grin&quot; ImageKey=&quot;img_emot2_grin&quot;&gt;
        ///    &lt;Text&gt;:D&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Code=&quot;emot wink&quot; Description=&quot;Wink&quot; ImageKey=&quot;img_emot2_wink&quot;&gt;
        ///    &lt;Text&gt;;)&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Code=&quot;emot surprised&quot; Description=&quot;Surprised&quot; ImageKey=&quot;img_emot2_surprised&quot;&gt;
        ///    &lt;Text&gt;:O&lt;/Text&gt;
        ///    &lt;Te [rest of string was truncated]&quot;;.
        /// </summary>
        public static string emoticon_defs {
            get {
                return ResourceManager.GetString("emoticon_defs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Emoticons&gt;
        ///  &lt;Emoticon Description=&quot;Smile&quot; Code=&quot;{\emot smile}&quot; ImageKey=&quot;mnuSmileySmile&quot;&gt;
        ///    &lt;Text&gt;:)&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Description=&quot;Grin&quot; Code=&quot;{\emot grin}&quot; ImageKey=&quot;mnuSmileyGrin&quot;&gt;
        ///    &lt;Text&gt;:D&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Description=&quot;Sad&quot; Code=&quot;{\emot sad}&quot; ImageKey=&quot;mnuSmileySad&quot;&gt;
        ///    &lt;Text&gt;:(&lt;/Text&gt;
        ///  &lt;/Emoticon&gt;
        ///  &lt;Emoticon Description=&quot;Cool&quot; Code=&quot;{\emot cool}&quot; ImageKey=&quot;mnuSmileyCool&quot;&gt;
        ///    &lt;Text&gt;B)&lt;/Text&gt;
        ///    &lt;Text&gt;8)&lt;/Tex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string emoticon_fallback {
            get {
                return ResourceManager.GetString("emoticon_fallback", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap FileIcon {
            get {
                object obj = ResourceManager.GetObject("FileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon HistoryIcon {
            get {
                object obj = ResourceManager.GetObject("HistoryIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_Blank {
            get {
                object obj = ResourceManager.GetObject("il_Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_Font {
            get {
                object obj = ResourceManager.GetObject("il_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_PopIn {
            get {
                object obj = ResourceManager.GetObject("il_PopIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_PopOut {
            get {
                object obj = ResourceManager.GetObject("il_PopOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_Save {
            get {
                object obj = ResourceManager.GetObject("il_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_SendFile {
            get {
                object obj = ResourceManager.GetObject("il_SendFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap il_Smiley {
            get {
                object obj = ResourceManager.GetObject("il_Smiley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_chat_available {
            get {
                object obj = ResourceManager.GetObject("img_chat_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_chat_away {
            get {
                object obj = ResourceManager.GetObject("img_chat_away", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_chat_busy {
            get {
                object obj = ResourceManager.GetObject("img_chat_busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_chat_donotdisturb {
            get {
                object obj = ResourceManager.GetObject("img_chat_donotdisturb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_chat_offline {
            get {
                object obj = ResourceManager.GetObject("img_chat_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_angry {
            get {
                object obj = ResourceManager.GetObject("img_emot_angry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_biggrin {
            get {
                object obj = ResourceManager.GetObject("img_emot_biggrin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_blink {
            get {
                object obj = ResourceManager.GetObject("img_emot_blink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_cool {
            get {
                object obj = ResourceManager.GetObject("img_emot_cool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_dry {
            get {
                object obj = ResourceManager.GetObject("img_emot_dry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_huh {
            get {
                object obj = ResourceManager.GetObject("img_emot_huh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_laugh {
            get {
                object obj = ResourceManager.GetObject("img_emot_laugh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_mellow {
            get {
                object obj = ResourceManager.GetObject("img_emot_mellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_ohmy {
            get {
                object obj = ResourceManager.GetObject("img_emot_ohmy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_rolleyes {
            get {
                object obj = ResourceManager.GetObject("img_emot_rolleyes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_sad {
            get {
                object obj = ResourceManager.GetObject("img_emot_sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_smile {
            get {
                object obj = ResourceManager.GetObject("img_emot_smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_tongue {
            get {
                object obj = ResourceManager.GetObject("img_emot_tongue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_unsure {
            get {
                object obj = ResourceManager.GetObject("img_emot_unsure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot_wink {
            get {
                object obj = ResourceManager.GetObject("img_emot_wink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_angry {
            get {
                object obj = ResourceManager.GetObject("img_emot2_angry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_beer {
            get {
                object obj = ResourceManager.GetObject("img_emot2_beer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_brokenheart {
            get {
                object obj = ResourceManager.GetObject("img_emot2_brokenheart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_bulb {
            get {
                object obj = ResourceManager.GetObject("img_emot2_bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_cake {
            get {
                object obj = ResourceManager.GetObject("img_emot2_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_call {
            get {
                object obj = ResourceManager.GetObject("img_emot2_call", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_camera {
            get {
                object obj = ResourceManager.GetObject("img_emot2_camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_cat {
            get {
                object obj = ResourceManager.GetObject("img_emot2_cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_coffee {
            get {
                object obj = ResourceManager.GetObject("img_emot2_coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_confused {
            get {
                object obj = ResourceManager.GetObject("img_emot2_confused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_cool {
            get {
                object obj = ResourceManager.GetObject("img_emot2_cool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_cry {
            get {
                object obj = ResourceManager.GetObject("img_emot2_cry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_dog {
            get {
                object obj = ResourceManager.GetObject("img_emot2_dog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_embarrassed {
            get {
                object obj = ResourceManager.GetObject("img_emot2_embarrassed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_gift {
            get {
                object obj = ResourceManager.GetObject("img_emot2_gift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_grin {
            get {
                object obj = ResourceManager.GetObject("img_emot2_grin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_halo {
            get {
                object obj = ResourceManager.GetObject("img_emot2_halo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_heart {
            get {
                object obj = ResourceManager.GetObject("img_emot2_heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_hug {
            get {
                object obj = ResourceManager.GetObject("img_emot2_hug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_huh {
            get {
                object obj = ResourceManager.GetObject("img_emot2_huh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_lips {
            get {
                object obj = ResourceManager.GetObject("img_emot2_lips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_mail {
            get {
                object obj = ResourceManager.GetObject("img_emot2_mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_messenger {
            get {
                object obj = ResourceManager.GetObject("img_emot2_messenger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_moon {
            get {
                object obj = ResourceManager.GetObject("img_emot2_moon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_movie {
            get {
                object obj = ResourceManager.GetObject("img_emot2_movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_music {
            get {
                object obj = ResourceManager.GetObject("img_emot2_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_rose {
            get {
                object obj = ResourceManager.GetObject("img_emot2_rose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_sad {
            get {
                object obj = ResourceManager.GetObject("img_emot2_sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_smile {
            get {
                object obj = ResourceManager.GetObject("img_emot2_smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_star {
            get {
                object obj = ResourceManager.GetObject("img_emot2_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_surprised {
            get {
                object obj = ResourceManager.GetObject("img_emot2_surprised", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_thumbsup {
            get {
                object obj = ResourceManager.GetObject("img_emot2_thumbsup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_time {
            get {
                object obj = ResourceManager.GetObject("img_emot2_time", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_tongue {
            get {
                object obj = ResourceManager.GetObject("img_emot2_tongue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_wink {
            get {
                object obj = ResourceManager.GetObject("img_emot2_wink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_emot2_witheredrose {
            get {
                object obj = ResourceManager.GetObject("img_emot2_witheredrose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_status_available {
            get {
                object obj = ResourceManager.GetObject("img_status_available", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_status_away {
            get {
                object obj = ResourceManager.GetObject("img_status_away", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_status_busy {
            get {
                object obj = ResourceManager.GetObject("img_status_busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_status_donotdisturb {
            get {
                object obj = ResourceManager.GetObject("img_status_donotdisturb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap img_status_offline {
            get {
                object obj = ResourceManager.GetObject("img_status_offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lblInfo {
            get {
                object obj = ResourceManager.GetObject("lblInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap lblTip {
            get {
                object obj = ResourceManager.GetObject("lblTip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBCopy {
            get {
                object obj = ResourceManager.GetObject("mnuMBCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBCut {
            get {
                object obj = ResourceManager.GetObject("mnuMBCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBDelete {
            get {
                object obj = ResourceManager.GetObject("mnuMBDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBPaste {
            get {
                object obj = ResourceManager.GetObject("mnuMBPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBRedo {
            get {
                object obj = ResourceManager.GetObject("mnuMBRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuMBUndo {
            get {
                object obj = ResourceManager.GetObject("mnuMBUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyAbout {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyExit {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyFileTransfers {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyFileTransfers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyHistory {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyOptions {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyOptions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mnuNotifyShow {
            get {
                object obj = ResourceManager.GetObject("mnuNotifyShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream newalert {
            get {
                return ResourceManager.GetStream("newalert", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream newmessage {
            get {
                return ResourceManager.GetStream("newmessage", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream online {
            get {
                return ResourceManager.GetStream("online", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap picBoxLogo {
            get {
                object obj = ResourceManager.GetObject("picBoxLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Statuses&gt;
        ///  &lt;Status Code=&quot;Available&quot; Selectable=&quot;true&quot; Description=&quot;Available&quot; StatusImage=&quot;img_status_available&quot; ChatImage=&quot;img_chat_available&quot;&gt;
        ///  &lt;/Status&gt;
        ///  &lt;Status Code=&quot;Busy&quot; Selectable=&quot;true&quot; Description=&quot;Busy&quot; StatusImage=&quot;img_status_busy&quot; ChatImage=&quot;img_chat_busy&quot;&gt;
        ///  &lt;/Status&gt;
        ///  &lt;Status Code=&quot;DoNotDisturb&quot; Selectable=&quot;true&quot; Description=&quot;Do Not Disturb&quot; StatusImage=&quot;img_status_donotdisturb&quot; ChatImage=&quot;img_chat_donotdisturb&quot;&gt;
        ///  &lt;/Status&gt;
        ///  &lt;Status Code= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string status_defs {
            get {
                return ResourceManager.GetString("status_defs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- Default &quot;Orange&quot; theme definition file --&gt;
        ///&lt;!-- Theme should have a name, else it will not show up in application --&gt;
        ///&lt;Theme name=&quot;Default&quot;&gt;
        ///  &lt;!-- This section describes the main window --&gt;
        ///  &lt;Main&gt;
        ///    &lt;BackColor&gt;70, 133, 185&lt;/BackColor&gt;
        ///    &lt;TextColor&gt;245, 245, 245&lt;/TextColor&gt;
        ///    &lt;!-- The top left panel where local user info is displayed --&gt;
        ///    &lt;PresencePane&gt;
        ///      &lt;BackColor&gt;188, 199, 216&lt;/BackColor&gt;
        ///      &lt;BorderColor&gt;188, 199, 216&lt;/BorderColor&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string theme_default {
            get {
                return ResourceManager.GetString("theme_default", resourceCulture);
            }
        }
    }
}
